FROM node:16.14-alpine3.14 AS base

FROM base AS deps

RUN apk add --no-cache libc6-compat
WORKDIR /app/next-project-default

COPY package*.json .
RUN npm ci --production --omit=dev


FROM base AS builder
WORKDIR /app/next-project-default
COPY --from=deps /app/next-project-default/node_modules ./node_modules
COPY . .

ENV NEXT_TELEMETRY_DISABLED 1


RUN npm run build && \
    npm prune --production && \
    npm cache clean --force && \
    rm -rf .next/cache && \
    rm -rf node_modules/.cache && \
    find . -name "*.test.*" -delete


FROM mhart/alpine-node:slim-14 AS runner 
WORKDIR /app/next-project-default

ENV NODE_ENV production

ENV NEXT_TELEMETRY_DISABLED 1

COPY --from=builder /app/next-project-default/public ./public
COPY --from=builder  /app/next-project-default/.next/standalone ./
COPY --from=builder /app/next-project-default/.next/static ./.next/static



ENV PORT 3000

CMD ["node", "server.js"]